version: '3.8'

services:
  jira-status-automation:
    build:
      context: .
      dockerfile: Containerfile
    container_name: jira-status-automation
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-8080}:${WEB_PORT:-8080}"
    environment:
      - WEB_PORT=${WEB_PORT:-8080}
      - TZ=${TZ:-UTC}
    volumes:
      # Data volume - for persistent data like last_run.txt
      - ./data:/app/data:rw
    command: python3 web_server.py --config /app/config/config.json --reports-dir /app/reports --host 0.0.0.0 --port ${WEB_PORT:-8080}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${WEB_PORT:-8080}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - jira-automation-network

  # Optional: Run scheduled reports in a separate container
  jira-status-scheduler:
    build:
      context: .
      dockerfile: Containerfile
    container_name: jira-status-scheduler
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      # Same volumes as the web server
      - ./data:/app/data:rw
    command: python3 scheduler.py --config /app/config/config.json --from-config
    depends_on:
      - jira-status-automation
    networks:
      - jira-automation-network
    profiles:
      - scheduler

networks:
  jira-automation-network:
    driver: bridge

volumes:
  jira-reports:
    driver: local
  jira-data:
    driver: local
